### ISSUE TITLE
EPIC #USER STORY# - DIV REGLER QiuzApp (1P)

### ISSUE THREAD

**Issue by sweets86** [EssaBarbar/QuizApp#27]
Som en deltagare vill jag se vilka regler som gäller för tävlingen för att kunna utföra tävlingen på rätt sätt.
(Skapa en Div och lägg in Regler för tävlingen.
Synligt på Webbsidan.)

Tidsbegränsad: 1h

Acceptanskriterier: Vi använder oss av programmet VisualStudioCode, installerat på datorn.
Valfri men fungerande browser.
Vi använder oss av informationen vi fått i projekt beskrivningen och även user storys nedan om poäng och antal spelare.

**Comment by medinstexjobb** [comment]
Henrik: 
Behöver denna VisualStudioCode vara en del av varje User Storys acceptanskriteria?

 "Vi använder oss av programmet VisualStudioCode, installerat på datorn."
