### ISSUE TITLE
EPIC #USER STORIES# - Spara POÄNGEN i databasen: (5P)

### ISSUE THREAD

**Issue by omerbasic** [EssaBarbar/QuizApp#4]
Som utvecklare vill jag spara poängen som varje deltagare får efter varje tävling i databasen för att kunna hämta ut det till topplistan.

Estimerad tid: 20 minuter

Acceptanskriterier: Vi använder oss av programmet VisualStudioCode, installerat på datorn.
Valfri men fungerande browser.
Tillgång till MAMP Server.

**Comment by medinstexjobb** [comment]
Bra User Story.

En fråga: 
Hur hanteras fel (error handling) ifall poängen inte kan sparas i databasen?
Hur beräknas poängen?
